# -*- coding: utf-8 -*-
"""Lesson8_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuzPWUZvTvtzThEgjWGyHRgQ8xoWgK2f
"""

import numpy as np
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

import numpy as np
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

import numpy as np
zeros_arr=np.zeros((3,3))
print(zeros_arr)

import numpy as np
zeros_arr=np.zeros((3,3,3))
print(zeros_arr)

import numpy as np
zeros_arr=np.zeros((2,4)) #ehleed mor tged bagana shu
print(zeros_arr)

import numpy as np
range_arr=np.arange(1,10,2) # 1 ees 10 hurtel 2-oor ihesgey
print(range_arr)

import numpy as np
random_arr = np.random.rand(2,3) # array with random values
print(random_arr)

import numpy as np
random_arr = np.random.rand(2,3) # array with random values
random_arr = np.random.rand(2,3)*100
print(random_arr)

import numpy as np
random_arr=np.random.rand(2,3)
print(random_arr.shape) #dimension bur dr heden utga bh we gedgiig
print(random_arr.size)
print(random_arr.ndim)
print(random_arr.dtype)

import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
sum=arr1+arr2
print(sum)

#reshaping an array
#text aragshaaga jagstsan bhad teden mortei bolgo ntr ged yanzalhad hereglene
import numpy as np
arr=np.arange(1,9) # negees 8 hurtleh too bn, 9 n orku
reshaped_arr=arr.reshape(2,4)
print(reshaped_arr)

#transposing an array
# moriig n bagana or baganiig n mor bolgochino

import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
transposed_arr=np.transpose(arr_2d)
print(arr_2d)
print(transposed_arr)

# Matrix multiplication
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dot(arr1,arr2)
print(result)

#kaggle.com deer lear gsn heseg bga, tendees pandas gedeg hesegt bgag ajilchaad ir